name: Build TeamCloud Runners

on:
  push:
    branches: [ main ]

jobs:

  core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image - runner
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./core
          file: ./core/Dockerfile
          platforms: linux/amd64
          tags: markusheiliger/tcrunner:latest
          push: true

  runner:
    needs: core
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        runner: ['arm', 'terraform']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image - ${{ matrix.runner }}
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./${{ matrix.runner }}
          file: ./${{ matrix.runner }}/Dockerfile
          platforms: linux/amd64
          tags: teamcloud/tcrunner-${{ matrix.runner }}:latest
          push: true

          
