name: Build TeamCloud Runners

on:
  push:
    branches: [ main ]

jobs:

  prepare:
    name: Prepare container build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with:
          useConfigFile: true

    outputs:
      version: ${{ steps.gitversion.outputs.assemblySemVer }}

  core:
    name: Build Core
    runs-on: ubuntu-latest
    needs: prepare

    env:
      CONTAINER_VERSION: ${{ needs.prepare.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image - runner
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./core
          file: ./core/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            teamcloud/tcrunner-core:latest
            teamcloud/tcrunner-core:${{ env.CONTAINER_VERSION }}

  runner:
    name: Build Runner 
    runs-on: ubuntu-latest
    needs: [ prepare, core ]
    
    env:
      CONTAINER_VERSION: ${{ needs.prepare.outputs.version }}

    strategy:
      max-parallel: 5
      matrix:
        runner: ['arm', 'terraform', 'helm']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push Docker image - ${{ matrix.runner }}
        uses: docker/build-push-action@v2.1.0
        with:
          context: ./${{ matrix.runner }}
          file: ./${{ matrix.runner }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            teamcloud/tcrunner-${{ matrix.runner }}:latest
            teamcloud/tcrunner-${{ matrix.runner }}:${{ env.CONTAINER_VERSION }}

          
